// const ele=document.querySelector("div");
// ele.remove();

// const ele= document.querySelector('div');
// const c= document.getElementById('id1');
// ele.removeChild(c);

// const ele1=document.querySelector('p:nth-of-type(2)');
// ele1.remove(ele1);

// function getinfo(e){
   
//     // const ele=document.querySelector('div');
//     // const ele2=document.createElement('p');
//     // ele2.innerHTML="my name is disha";
//     // ele.prepend(ele2);

//     console.log(e);
//     e.target.style.backgroundColor='green';
//     e.target.style.color='red';
// }







